In [2]:
import numpy as np
from numpy import random

In [5]:
arr1 = random.rand(2,2)  # random array, shape = arguements, distribution= uniform between 0 to 1.
print(arr1)

[[0.11546384 0.86318478]
 [0.89375466 0.9354978 ]]


In [7]:
arr2 = random.randn(2,2)  # random array, shape = arguements, distribution = Standard normal (mean = 0, std =1)
print(arr2)

[[ 2.65236129  0.53385437]
 [-0.14811159 -1.4587515 ]]


In [10]:
arr3 = random.randint(low = 2 ,high = 10, size = (2,2) ) # distribution = Discrete Uniform
print(arr3)

[[3 7]
 [4 2]]


In [17]:
arr4 = np.linspace(start = 10.0, stop = 20.0, num = 5, retstep = True ) # return evenly spaced numbers 
print(arr4)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)
